var cadenaCodificada = "UmVjdWVyZGEgcXVlIGN1YW5kbyBjb2RpZmljYXMgYWxnbyBlbiBiYXNlNjQgTk8gbG8gZXN0w6FzIGNpZnJhbmRvLCBzaW5vIHF1ZSBzaW1wbGVtZW50ZSBsbyBlc3TDoXMgY29kaWZpY2FuZG8uDQoNCkxhIGNvbnRyYXNlw7FhIHBhcmEgc3VwZXJhciBlc3RlIHJldG8gZXM6IHJlY3VlcmRhcXVlYmFzZTY0Tk9lc2NpZnJhcg0KCg==";
var cadenaDecodificada = atob(cadenaCodificada);
console.log(cadenaDecodificada); // Esto imprimirá "Hola Mundo!"